export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_SIDEBAR_REQUEST = 'GET_SIDEBAR_REQUEST';
export const GET_SIDEBAR_SUCCESS = 'GET_SIDEBAR_SUCCESS';
export const GET_SIDEBAR_ERROR = 'GET_SIDEBAR_ERROR';

export const GET_TABS_REQUEST = 'GET_TABS_REQUEST';
export const GET_TABS_SUCCESS = 'GET_TABS_SUCCESS';
export const GET_TABS_ERROR = 'GET_TABS_ERROR';
export const UPDATE_TABS_SUCCESS = 'UPDATE_TABS_SUCCESS';

export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR';

export const UPDATE_LAYOUT_SUCCESS = 'UPDATE_LAYOUT_SUCCESS';
export const REMOVE_LAYOUT_ITEM_SUCCESS = 'REMOVE_LAYOUT_ITEM_SUCCESS';